name: whistle-music-synthesizer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8
  - numpy=1.24.3
  - scipy=1.10.1
  - matplotlib=3.7.1
  - librosa=0.10.1
  - soundfile=0.12.1
  - pretty_midi=0.2.9
  - mido=1.2.10
  - tqdm=4.65.0
  - pandas=2.0.2
  - scikit-learn=1.3.0
  - jupyter=1.0.0
  - ipykernel=6.23.1
  - pip=23.1.2
  - pip:
    - tensorboard==2.13.0
    - wandb==0.15.5
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - music21==9.1.0
    - pyfluidsynth==1.3.1
